# Generated by Django 5.2.7 on 2025-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_date_of_birth_alter_pet_slug'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
