# Generated by Django 5.2.7 on 2025-11-28 22:24

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='files', validators=[photos.validators.SizeCheck(5)]),
        ),
    ]
