# Generated by Django 5.2.7 on 2025-11-28 23:02

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='files', validators=[photos.validators.SizeCheck(100)]),
        ),
    ]
